name: Admin Lint

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 lint:
   runs-on: ubuntu-latest
   "steps": [
     {
       "uses": "actions/checkout@v4"
     },
     {
       "id": "python",
       "name": "Set up Python 3.11",
       "uses": "actions/setup-python@v5",
       "with": {
         "check-latest": true,
         "python-version": "3.11"
       }
     },
     {
       "name": "Install and configure Poetry",
       "uses": "snok/install-poetry@v1",
       "with": {
         "installer-parallel": true,
         "virtualenvs-create": true,
         "virtualenvs-in-project": true
       }
     },
     {
       "if": "steps.cache-venv.outputs.cache-hit != 'true'",
       "name": "Install dependencies",
       "run": "poetry install --no-interaction --no-root"
     },
     {
       "name": "Run lintrunner",
       "run": ". .venv/bin/activate\nlintrunner --all-files"
     }
