name: Admin Lint

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 lint:
   runs-on: ubuntu-latest
   steps:
    - name: "Checkout code"
      uses: "actions/checkout@v4"

    - name: "Set up Python 3.11"
      uses: "actions/setup-python@v5"
      with:
       check-latest: true
       python-version: "3.11"
    - name: "Install dependencies"
      run: "pip install --upgrade pip && pip install ruff"
    - name: "Run lint checker"
      run: "ruff check"
